name: mobilebita
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  camera: ^0.11.0
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  file_picker: ^10.1.9
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  get: ^4.6.5
  http: ^0.13.5
  image_picker: ^1.1.1
  intl: ^0.18.1
  shared_preferences: ^2.5.3
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  flutter_tts: ^3.5.2
  image: ^4.0.17

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/splash/splashscreen.png
    - assets/person1.png
    - assets/deteksi.png
    - assets/transcrib.png
    - assets/kamus.png
    - assets/person2.png
    - assets/google.png
    - assets/alfabet.png
    - assets/kata_tanya.png
    - assets/kata_kerja.png
    - assets/kata_sifat.png
    - assets/abc.png
    - assets/question.png
